### ISSUE TITLE
Unknown type pet 17447 is summoned by player class 4

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-npc-beastmaster#33]
When summoning a pet with another class than hunter, I get this:

`Unknown type pet 17447 is summoned by player class 4`

i suppose it's because I didn't apply the core patch, right?

Note: this issue will be there for reference because I'm pretty sure the answer is to apply the patch

**Comment by Stoabrogga** [comment]
Yes. I'm currently working on new PlayerScript hooks which render the patch obsolete, but this will take some more time.

**Comment by BarbzYHOOL** [comment]
ok feel free to close this

**Comment by Stoabrogga** [comment]
ok, will do this once the hooks are in place and the changes for beastmaster are merged.
