### ISSUE TITLE
Gargoyle ultimate talent for Unholy DK is not doing any damage because of this module

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-npc-beastmaster#38]
https://github.com/azerothcore/azerothcore-wotlk/issues/3053

I use it with:
```
BeastMaster.HunterOnly = 1
```

This is a critical issue.

**Comment by BarbzYHOOL** [comment]
Maybe need to fix the core too, cf https://github.com/azerothcore/azerothcore-wotlk/commit/3f0739f1c9a5289444ff9d62834b7ceb38879ba9

**Comment by BarbzYHOOL** [comment]
fixed, thank you barbz

**Comment by Helias** [comment]
lol
