### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by valleyss** [azerothcore/mod-npc-beastmaster#54]
warning: 'GetBoolDefault' is deprecated: Use GetOption<bool> instead [-Wdeprecated-declarations]
        BeastMasterAnnounceToPlayer = sConfigMgr->GetBoolDefault("BeastMaster.Announce", true);
Config.h:57:7: note: 'GetBoolDefault' has been explicitly marked deprecated here
    [[deprecated("Use GetOption<bool> instead")]]
warning: 'GetBoolDefault' is deprecated: Use GetOption<bool> instead [-Wdeprecated-declarations]
        BeastMasterHunterOnly = sConfigMgr->GetBoolDefault("BeastMaster.HunterOnly", true);

**Comment by acidmanifesto** [comment]
[878c017](https://github.com/azerothcore/mod-npc-beastmaster/commit/878c0170b5f079408d200d5abf9f619678a60281)
